name: Build PS4 Linux Payloads

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang llvm yasm

      - name: Build PS4 payloads in linux/
        run: |
          cd linux
          make

      - name: Upload all firmware payloads with folder structure
        uses: actions/upload-artifact@v4
        with:
          name: ps4-payloads
          path: |
            linux/fw*/*.bin
